codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: up
  range: "75...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  branches:
    - latest
    - latest-next
    - next
    - beta
    - alpha
